# Generated by Django 4.2.4 on 2023-08-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('google_drive_file_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('google_drive_user_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=20)),
                ('visibility', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('google_drive_user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
