# Generated by Django 4.2.4 on 2023-08-10 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_file_can_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='google_drive_user_id',
        ),
        migrations.AddField(
            model_name='file',
            name='google_drive_user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('Critico', 'Critico'), ('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Pendiente', 'Pendiente'), ('Anulado', 'Anulado')], default='Pendiente', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('google_drive_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.file')),
            ],
        ),
    ]
