# Generated by Django 4.2.4 on 2023-08-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_file_google_drive_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='google_drive_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.file'),
        ),
    ]
