# Generated by Django 4.2.4 on 2023-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_poll_google_drive_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='google_drive_file',
        ),
        migrations.AddField(
            model_name='poll',
            name='google_drive_file_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
