# Generated by Django 4.2.4 on 2023-08-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_poll_google_drive_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_tipe',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
