# Generated by Django 4.2.4 on 2023-08-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_file_mime_tipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='mime_tipe',
            new_name='mime_type',
        ),
    ]
