# Generated by Django 4.2.4 on 2023-08-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_mime_tipe_file_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(max_length=200),
        ),
    ]
