# Generated by Django 4.2.4 on 2023-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_poll_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='commentary',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='classification',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
