# Generated by Django 4.2.4 on 2023-08-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_classification_commentary_file_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.TextField(),
        ),
    ]
